linkPrefix = ''
# linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

siteHost = 'Numenta.com'
siteTitle = 'Numenta'
description = 'Leading the New Era of Machine Intelligence'

[contact]
  [contact.email]
    feedback = 'feedback@numenta.com'
    info = 'info@numenta.com'
    press = 'press@numenta.com'
    sales = 'sales@numenta.com'
    support = 'support@numenta.com'
  [contact.phone]
    fax = '650-369-8283'
    tel = '650-369-8282'

[analytics]
  google = 'UA-48460134-1'

[links]
  [links.out]  # external links
    # apps
    grokGet = 'http://grokstream.com/#pricing'
    geo = 'https://github.com/numenta/nupic.geospatial'
    rogue = 'https://github.com/numenta/nupic.rogue'
    # legal
    license = 'http://numenta.org/licenses/'
    trial = 'http://numenta.org/licenses/trial/'
    # partners
    cortical = 'http://cortical.io'
    grok = 'http://grokstream.com'
    org = 'http://numenta.org'
    # social
    facebook = 'https://www.facebook.com/pages/Numenta/321559142118?ref=br_tf'
    linkedin = 'https://www.linkedin.com/company/numenta'
    map = 'http://maps.google.com/maps?q=791+Middlefield+Road,+Redwood+City,+CA+94063'
    twitter = 'https://twitter.com/numenta'
    youtube = 'https://www.youtube.com/user/numenta'
    [links.out.htmstocks]
      app = 'https://itunes.apple.com/us/app/htm-for-stocks/id1049429350?mt=8'
      play = 'https://play.google.com/store/apps/details?id=com.numenta.taurus'
    [links.out.htmstudio]
      macos = 'http://public.numenta.com/releases/htm-studio/darwin/HTM%20Studio-1.0.0.dmg'
      windows = 'http://public.numenta.com/releases/htm-studio/win/HTM%20Studio%20Setup%201.0.0.exe'

  [links.in]  # internal paths
    # main/home pseudo-single page
    home = '/'
    mission = '/mission-and-history/'
    technology = '/technology-overview/'
    opensource = '/open-source-project/'
    applications = '/applications/'
    benchmark = '/anomaly-detection-benchmark/'
    partners = '/partners/'
    business = '/business-strategy-and-ip/'
    papers = '/papers-videos-and-more/'
    careers = '/careers-team-and-contact/'
    # other site pages
    bami = '/biological-and-machine-intelligence/'
    blog = '/blog/'
    events = '/events/'
    htmstocks = '/htm-for-stocks/'
    htmstudio = '/htm-studio/'
    nab = '/numenta-anomaly-benchmark/'
    newsletter = '/newsletter/'
    press = '/press/'
    privacy = '/legal/privacy/'
    sitemap = '/sitemap/'
    terms = '/legal/terms/'

  [links.anchor]  # internal path anchor hashes
    # mission
    mission = '#mission'
    history = '#history'
    # applications
    htmstudio = '#htmstudio'
    htmstocks = '#htmstocks'
    grokit = '#grokit'
    rogue = '#rogue'
    geo = '#geo'
    nlp = '#nlp'
    # partners
    cortical = '#cortical'
    grok = '#grok'
    # business
    transparency = '#transparency'
    science = '#science'
    deployment = '#deployment'
    licenses = '#licenses'
    faq = '#faq'
    # careers
    careers = '#careers'
    team = '#team'
    board = '#board'
    contact = '#contact'
    office = '#office'
    follow = '#follow'
    # other pages
    get = '#get'  # htmstocks, etc.
    links = '#links'  # press links

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
