linkPrefix = ''
# linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

siteHost = 'Numenta.org'
siteTitle = 'Numenta HTM Community'
description = 'Numenta Hierarchical Temporal Memory (HTM) Community and Resources'

[contact]
  [contact.email]
    info = 'info@numenta.org'

[analytics]
  google = 'UA-40622508-1'
  pingdom = '55a7dbc8abe53dba666b928b'

[links]
  [links.out]  # external links
    bami = 'http://numenta.com/biological-and-machine-intelligence/'
    com = 'http://numenta.com/'
    cortical = 'http://cortical.io/'
    grok = 'http://grokstream.com/'
    forum = 'https://discourse.numenta.org/categories'

  [links.in]  # internal paths
    # main/home pseudo-single page
    home = '/'
    research = '/research-and-publications/'
    community = '/community/'
    implement = '/implementations/'
    school = '/htm-school/'
    # other site pages
    blog = '/blog/'
    conduct = '/'  # @TODO
    events = '/events/'
    htm = '/hierarchical-temporal-memory/'
    # @TODO licenses
    papers = '/papers/'
    privacy = '/legal/privacy/'
    sitemap = '/sitemap/'
    terms = '/legal/terms/'

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
