linkPrefix = ''
#linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

baseUrl = 'https://numenta.com'
#baseUrl = 'http://staging.numenta.com'

siteHost = 'Numenta.com'
siteTitle = ''
description = 'Where Neuroscience Meets Machine Intelligence'
company = 'Numenta'
logo = "/assets/img/logo.png"
[contact]
  [contact.email]
    feedback = 'feedback@numenta.com'
    info = 'info@numenta.com'
    press = 'press@numenta.com'
    sales = 'sales@numenta.com'
    licenses = 'licenses@numenta.com'
    support = 'support@numenta.com'
  [contact.phone]
    fax = '650-369-8283'
    tel = '650-369-8282'

[analytics]
  google = 'UA-48460134-1'
  pingdom = '569029d1abe53daf465fa724'

[links]
  [links.out]  # external links
    # apps
    apps = 'https://github.com/numenta/numenta-apps'
    grokGet = 'http://grokstream.com/#pricing'
    geo = 'https://github.com/numenta/nupic.geospatial'
    rogue = 'https://github.com/numenta/nupic.rogue'
    # legal
    patents = 'http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Numenta&FIELD1=ASNM&co1=AND&TERM2=&FIELD2=&d=PTXT'
    trial = 'http://numenta.org/licenses/trial/'
    # partners
    cortical = 'http://cortical.io'
    grok = 'http://grokstream.com'
    its = 'http://www.intelletic.com'
    # Org
    org = 'http://numenta.org'
    # social
    facebook = 'https://www.facebook.com/officialnumenta'
    linkedin = 'https://www.linkedin.com/company/numenta'
    map = 'http://maps.google.com/maps?q=791+Middlefield+Road,+Redwood+City,+CA+94063'
    twitter = 'https://twitter.com/numenta'
    # YouTube
    [links.out.htmschool]
      channel = 'https://www.youtube.com/OfficialNumenta'
      sptalk = 'https://www.youtube.com/watch?v=1r6GxDsEdd0'
      episode7 = 'https://www.youtube.com/watch?v=R5UoFNtv5AU'
      episode8 = 'https://www.youtube.com/watch?v=rHvjykCIrZM'
      episode9 = 'https://www.youtube.com/watch?v=MSwoNAODrgk'


  [links.in]  # internal paths
    # main/home pseudo-single page
    papers = '/neuroscience-research/research-publications/papers/'
    outsideresearch = '/neuroscience-research/research-publications/outside-research/'
    sppaper = '/neuroscience-research/research-publications/papers/htm-spatial-pooler-neocortical-algorithm-for-online-sparse-distributed-coding/'
    posters = '/neuroscience-research/research-publications/posters/'
    publications = '/neuroscience-research/research-publications/'
    neuro = '/neuroscience-research/'

    businessprinciples = '/machine-intelligence-technology/licensing-and-partners/business-principles/'
    licensingfaq = '/machine-intelligence-technology/licensing-and-partners/licensing-faq/'
    partners = '/machine-intelligence-technology/licensing-and-partners/'
    nutshell = '/machine-intelligence-technology/numenta-in-a-nutshell/'
    business = '/machine-intelligence-technology/business-strategy-and-ip/'
    technology = '/machine-intelligence-technology/'

    mission = '/company/mission-and-history/'
    careers = '/company/careers-and-team/'
    events = '/company/events/'
    newsletter = '/company/newsletter/'

    spweb = '/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/'
    tm = '/resources/biological-and-machine-intelligence/temporal-memory-algorithm/'
    bami = '/resources/biological-and-machine-intelligence/'

    opensource = '/resources/open-source-community/'
    papersvideos = '/resources/videos-podcasts-and-more/'
    videos = '/resources/videos/'
    numentaonintelligencepodcast = '/resources/numenta-on-intelligence-podcast/'
    podcasts = '/resources/podcasts/'
    onintelligence = '/resources/on-intelligence/'
    resources = '/resources/'

    anomaly = '/machine-intelligence-technology/numenta-anomaly-benchmark/'
    htmstudio = '/machine-intelligence-technology/htm-studio/'
    nab = '/machine-intelligence-technology/numenta-anomaly-benchmark/'
    applications = '/machine-intelligence-technology/applications/'

    contact = '/contact/'
    blog = '/blog/'
    sitemap = '/sitemap/'

    license = '/assets/pdf/apps/licensing-guide.pdf'
    htmforstocks = '/assets/pdf/apps/htmforstocks.pdf'
    sppdf = '/assets/pdf/spatial-pooling-algorithm/Spatial-Pooling-Algorithm-Details.pdf'

    pressreleases = '/press/releases/'
    presslinks = '/press/links/'
    press = '/press/'

    privacy = '/legal/privacy/'
    terms = '/legal/terms/'

    home = '/'
    [links.in.slides]
      sptalk = '/assets/pdf/spatial-pooling-algorithm/HTM-Spatial-Pooler-Overview.pdf'

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
